config/routes.rb
Rails.application.routes.draw do

  authenticate :user do
    resources :users
    root 'dashboard#index'
  end

  resources :accounts, only: [:new, :create]

  devise_for :users,
   path: "",
   path_names: {
    sign_in: "login",
    sign_out: "logout",
    sign_up: "signup"
  }

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id          :integer          not null, primary key
#  name        :string(255)      default(""), not null
#  website_url :string(255)
#  owner_id    :integer          default(0), not null
#  created_at  :datetime
#  updated_at  :datetime
#

class Account < ApplicationRecord

  validates :owner, presence: true
  belongs_to :owner, class_name: "User"
  has_many :users, inverse_of: :organization

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)      default(""), not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  invitation_token       :string(255)
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string(255)
#  invited_by_id          :integer
#  invitations_count      :integer          default(0)
#  organization_id        :integer
#  avatar_file_name       :string(255)
#  avatar_content_type    :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#

class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :invitable

  validates :email, presence: true, uniqueness: true
  validates_format_of :email,:with => Devise::email_regexp
  validates_presence_of :name

  has_one :account, foreign_key: "owner_id", inverse_of: :owner
  belongs_to :organization, class_name: "Account", inverse_of: :users

  attr_accessor :invitation_message

  enum role: [:user,:admin]  unless instance_methods.include? :role

  has_attached_file :avatar, styles: {
    thumb: '76x76>',
    square: '200x200#',
    medium: '300x300>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def abbr
    self.name.split(" ").map { |l| l[0] }.join("")
  end

  protected

  def password_required?
   !persisted? || !password.blank? || !password_confirmation.blank?
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def new
    @account = Account.new
    render layout: 'devise'
  end

  def create
    @account = Account.new(account_params)
    @account.owner = current_user
    respond_to do |format|
      if @account.save
        current_user.organization = @account
        current_user.role = User.roles[:admin]
        if current_user.save
          format.html { redirect_to root_path, notice: 'Required information save successfully.' }
        else
          format.html { render :new }
        end
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def destroy

  end

  private

  def account_params
    params.require(:account).permit(:name, :website_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :reset_session

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:accept_invitation, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
  end

  def authenticate_inviter!
    current_user || authenticate_user!
  end

  def after_sign_in_path_for(resource)
    if resource.sign_in_count == 1 and resource.organization == nil
      new_account_path
    else
      root_path
    end
  end

  def after_invite_path_for(*)
    users_path
  end

  private

  def authorizated_roles (*roles)
    roles.any? { |role_name| User.roles[role_name] == User.roles[current_user.role] }
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action { authorizated_roles(:user, :admin) }

  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage

  layout "landing"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  #before_action except: [:profile] { authorizated_roles(:admin)}
  #before_action only:   [:profile] { authorizated_roles(:user,:admin)}

  after_action :save_my_previous_url, only: [:new,:edit]

  def save_my_previous_url
    # session[:previous_url] is a Rails built-in variable to save last url.
    session[:my_previous_url] = URI(request.referer || '').path
  end

  def index
    @users = User.all.where(organization: current_user.organization)
  end

  def profile
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.invite!({:email => params[:user][:email],
                          :name => params[:user][:name],
                          :role => params[:user][:role],
                          :organization_id => current_user.organization_id},
                          current_user)
    respond_to do |format|
       if @user.persisted?
         format.html { redirect_to session[:my_previous_url], notice: 'User was successfully created.' }
       else
         format.html { render :new }
       end
     end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to session[:my_previous_url], notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email,:password, :avatar, :role, :name,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_menu path
    return "active" if current_page?(path)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    html = <<-HTML
    <div class="alert alert-danger" id="flash_alert">
      #{resource.errors.full_messages.join}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def card_border user
    return current_user == user ? "you-admin-border" :
           user.admin? ? 'user-admin-border' : 'user-normal-border'
  end

  def role_description(role)
    case role
    when "user"
      return "Has access full access except for billing, user-management."
    when "admin"
      return "Account user with full access"
    end
  end
end

app/views/accounts/new.html.erb
<nav class="navbar navbar-transparent navbar-absolute">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Sass Boilerplate", root_path, class: "navbar-brand" %>
    </div>
  </div>
</nav>
<div class="wrapper wrapper-full-page">
  <div class="full-page login-page">
    <div class="content">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
          <%= simple_form_for(@account, url: accounts_path) do |f| %>
          <div class="card" data-background="color" data-color="blue">
            <div class="card-header">
              <h3 class="card-title">Required Information</h3>
              <p>This is the first time you log in, so we need to you to complete
                this information to tailor your experience better.</p>
            </div>
            <%= f.error_notification %>
            <% flash.each do |name, msg| %>
              <%= content_tag :div, msg,:class => "alert alert-danger", :id => "flash_#{name}" if msg.is_a?(String) %>
            <%end%>
            <div class="card-content">
              <div class="form-group">
                <%= f.label :name, "Organization name" %>
                <%= f.input_field :name, class: "form-control input-no-border" %>
              </div>
            </div>
            <div class="card-footer text-center">
              <%= f.submit "Let's do it!", :class => 'btn btn-fill btn-wd' %>
            </div>
          </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>
    <footer class="footer footer-transparent">
      <div class="container">
        <div class="copyright">
          ©2017, made with <i class="fa fa-heart heart"></i> by Sass Boilerplate
        </div>
      </div>
    </footer>
    <div class="full-page-background"></div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-12">
    <div class="hpanel">
      <div class="panel-body">

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sass Genesis" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sass Boilerplate" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Muli:400,300" rel="stylesheet" type="text/css">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <%= favicon_link_tag 'favicon-152.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="wrapper">
      <%= render "layouts/shared/application/menu" %>
      <div class="main-panel">
        <%= render "layouts/shared/application/header" %>
        <div class="content">
          <%= yield %>
        </div>
        <footer class="footer">
					<div class="container-fluid">
						<nav class="pull-left">
							<ul>
								<li>
									<a href="http://www.creative-tim.com">
										Creative Tim
									</a>
								</li>
								<li>
									<a href="http://blog.creative-tim.com">
										Blog
									</a>
								</li>
								<li>
									<a href="http://www.creative-tim.com/license">
										Licenses
									</a>
								</li>
							</ul>
						</nav>
						<div class="copyright pull-right">
              <span>© <%= Date.today.year %> Copyright &amp;</span>
							 Made with <i class="fa fa-heart heart"></i> by <a href="http://www.creative-tim.com">Paul Anthony McGowan</a>
						</div>
					</div>
				</footer>
      </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <% flash_message = flash.map { |name,msg| msg if msg.is_a?(String) }.join('<br>') %>
    <% if !flash_message.empty? %>
      <script>
        $(document).ready(function() {
          $.notify({
            message: '<%= flash_message %>'
          },{
            type: 'warning'
          });
        });
      </script>
    <% end %>
    <%= yield :modals %>
    <%= yield :scripts %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sass Boilerplate" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sass Boilerplate" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Muli:400,300" rel="stylesheet" type="text/css">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <%= favicon_link_tag 'favicon-152.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= yield :scripts %>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sass Boilerplate" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sass Boilerplate" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Muli:400,300" rel="stylesheet" type="text/css">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">   
    <%= favicon_link_tag 'favicon-152.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="color-line"></div>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= yield :scripts %>
  </body>
</html>

app/views/layouts/shared/application/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar bar1"></span>
        <span class="icon-bar bar2"></span>
        <span class="icon-bar bar3"></span>
      </button>
      <a class="navbar-brand" href="#"><%= content_for?(:page_title) ? yield(:page_title) : "Dashboard" %></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="ti-bell"></i>
            <p class="notification">5</p>
            <p>Notifications</p>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#">Notification 1</a></li>
            <li><a href="#">Notification 2</a></li>
            <li><a href="#">Notification 3</a></li>
            <li><a href="#">Notification 4</a></li>
            <li><a href="#">Another notification</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <p><%= current_user.name %></p>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", edit_user_path(current_user) %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/shared/application/_menu.html.erb
<div class="sidebar" data-background-color="white" data-active-color="danger">
  <div class="sidebar-wrapper">
    <div class="logo">
      <a href="http://www.creative-tim.com" class="simple-text">SaaS Genesis</a>
    </div>

    <ul class="nav">
      <li class="<%= active_menu root_path %>">
        <%= link_to root_path do %>
          <i class="ti-panel"></i>
          <p>Dashboard</p>
        <% end %>
      </li>
      <% if current_user.admin? %>
        <li class="<%= active_menu users_path %>">
          <%= link_to users_path do %>
            <i class="fa fa-users"></i>
            <p>Team Members</p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/landing.html.erb
<div class="hero">
  <h1>We are a cool startup in the recruitment business</h1>
  <%= link_to "Create account!", new_account_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/users/_form.html.erb
<% content_for :scripts do %>
  <script type="text/javascript">
    $(document).ready(function () {
      $('#user_avatar').on('change', function(event) {
        var files = event.target.files;
        var image = files[0]
        var reader = new FileReader();
        reader.onload = function(file) {
          var img = new Image();
          console.log(file);
          img.src = file.target.result;
          $('#target').html(img);
        }
        reader.readAsDataURL(image);
        console.log(files);
      });
    });
  </script>
<% end %>
<%= simple_form_for @user do |f| %>
<div class="card">
  <div class="card-header">
    <h4 class="card-title">Profile Picture</h4>
  </div>
  <div class="card-content">
    <div id="target" class="profile-edit-image">
      <%= image_tag @user.avatar.url(:thumb) if @user.avatar.exists? %>
      <%= @user.abbr if !@user.avatar.exists? %>
    </div>
    <div class="profile-edit-image-content">
      <h4 style="margin-top:0px;">Upload your photo...</h4>
      <p>Photo should be at least 300px x 300px</p>
      <label for="user_avatar" class="custom-file-upload btn btn-primary btn-fill btn-wd">
        <i class="fa fa-cloud-upload"></i> Upload photo
        <%= f.input :avatar,as: :file, multiple: true, label: false %>
      </label>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Basic Information</h4>
      </div>
      <div class="card-content">
        <div class="form-group">
          <%= f.label :name, required:false %>
          <%= f.input :name, label: false, :input_html => {class: "form-control border-input"} %>
        </div>
        <div class="form-group">
          <%= f.label :email, required:false %>
          <%= f.input :email, label: false, :input_html => {class: "form-control border-input"} %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Change Password</h4>
      </div>
      <div class="card-content">
        <div class="form-group">
          <%= f.label :password, "New Password", required:false %>
            <%= f.input :password, label: false, :input_html => {class: "form-control border-input", autocomplete: "off"} %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Confirm new password", required:false %>
          <%= f.input :password_confirmation, label: false, :input_html => {class: "form-control border-input", autocomplete: "off"} %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="form-actions">
  <%= f.button :submit,class: "btn btn-primary btn-fill btn-wd" %>
</div>
<% end %>

app/views/users/edit.html.erb
<% content_for :page_title do %>
Edit User
<% end %>
<%= render 'form' %>

app/views/users/index.html.erb
<% content_for :page_title do %>Team members<% end %>
<% content_for :scripts do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $("[data-behavior='delete']").on('click',function(e) {
        e.preventDefault();
        var url = $(this).attr("href");
        var el = $(this).parents(".card");
        swal({
          title: "Are you sure?",
          text:  "You will not be able to recover this user",
          type:  "warning",
          confirmButtonColor: '#d9534f',
          confirmButtonText: 'Yes, delete it!',
          cancelButtonText: 'No, cancel!',
          closeOnConfirm: false,
          showCancelButton: true,
          closeOnCancel: true,
          showLoaderOnConfirm: true
        }, function(confirmed) {
          if (confirmed) {
            $.ajax({
              url: url,
              dataType: "JSON",
              method: "DELETE",
              success: function() {
                swal('Deleted!','The user has been deleted','success');
                el.remove();
              }
            });
          }
        });
      });
    });
  </script>
<% end %>
<div class="clearfix">
  <%= link_to "Invite User", new_user_path, class: 'btn btn-default btn-fill btn-wd mb-21' %>
  <div>
    <span class="legend-item"><span class="label label-danger">&nbsp;</span> You </span>
    <span class="legend-item"><span class="label label-warning">&nbsp;</span> Admin users</span>
    <span class="legend-item"><span class="label label-primary">&nbsp;</span> Normal users</span>
  </div>
</div>
<br/>

<% @users.each_slice(4) do |rows| %>
  <div class="row mb-7">
    <% rows.each do |user| %>
      <div class="col-md-3">
        <div class="card <%= card_border(user) %>">
          <div class="card-content clearfix">
            <%= image_tag user.avatar.url(:thumb), class: 'img-circle img-no-padding img-responsive avatar' if user.avatar.exists? %>
            <% if !user.avatar.exists? %>
              <div class="img-circle m-b profile-empty-image">
                <%= user.name[0]%>
              </div>
            <% end %>
            <span class="user-title mb-7"><%= user.name %></span><br>
            <small><%= user.email %></small>
            <hr class="mb-0">
          </div>
          <div class="card-footer text-right">
            <%= link_to edit_user_path(user), class:"btn btn-icon" do %>
              <i class="fa fa-pencil"></i>
            <% end %>
            <% if current_user != user %>
              <%= link_to user_path(user), data: { behavior: 'delete'}, class: "btn btn-icon btn-danger" do %>
                <i class="fa fa-trash"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<% content_for :scripts do %>
  <script type="text/javascript">
    $().ready(function() {

      $.validator.addMethod("customEmail",
          function(value, element) {
              return /^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/.test(value);
          },
          "Please enter a valid email address."
      );

      $("form").validate({
        rules: {
          "user[email]" : {
            required: true,
            customEmail: true
          },
          "user[role]": {
            required: true
          }
        },
        submitHandler: function(form) {
          form.submit();
        },
        errorPlacement: function(error, element) {
          switch (element.attr("name")) {
            case "user[role]":
              $(element).parents(".col-sm-10").append(error);
              break;
            default:
              error.insertAfter(element);
          }
        }
      });
    });
</script>
<% end %>
<% content_for :page_title do %>
  Invite User
<% end %>
<% if @user.errors.any? %>
  <div class="alert alert-warning">
    <% @user.errors.full_messages.each do |message| %>
    <p><%= message %></p>
    <% end %>
  </div>
<% end %>
<div class="card col-sm-7 col-lg-5">
  <div class="card-content">
    <%= simple_form_for @user, :html => { class: "form-horizontal"} do |f| %>
      <div class="form-group">
        <%= f.label :name, class: "col-sm-2 control-label", required:false %>
        <div class="col-sm-10">
          <%= f.input :name, label: false, required:false, :input_html => {class: "form-control"} %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, class: "col-sm-2 control-label", required:false %>
        <div class="col-sm-10">
          <%= f.input :email, label: false, :input_html => {class: "form-control"} %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">User Type</label>
        <div class="col-sm-10">
          <% User.roles.keys.each do |role| %>
            <% if role != "transcriptor" %>
              <div class="radio pt-0">
                <label class="pl-0">
                  <input class="radio_buttons optional form-control i-checks"
                  type="radio"
                  <%= 'checked' if role == "user" %>
                  value="<%= role %>"
                  name="user[role]"
                  id="user_role_<%= role %>">
                  <span style="font-weight:bold;"><%= I18n.t("activerecord.attributes.user.role.#{role}") %></span>
                  <p><%= role_description(role) %></p>
                </label>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Invite User", class: "btn btn-primary btn-fill btn-wd" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :page_title do %>
  <div class="small-header">
      <div class="hpanel">
          <div class="panel-body">
              <div id="hbreadcrumb" class="pull-right">
                  <ol class="hbreadcrumb breadcrumb">
                      <li><%= link_to "Dashboard", root_path %></li>
                      <li>
                          <span>Users</span>
                      </li>
                      <li class="active">
                          <span>Profile</span>
                      </li>
                  </ol>
              </div>
              <h2 class="font-light m-b-xs">
                  Profile
              </h2>
              <small>Your personal information</small>
          </div>
      </div>
  </div>
<% end %>